__author__ = "NuoDB, Inc."
__copyright__ = "(C) Copyright NuoDB, Inc.  2019-2020"
__license__ = "MIT"
__version__ = "1.1.0"
__maintainer__ = "NuoDB Drivers"
__email__ = "drivers@nuodb.com"
__status__ = "Production"
