#!/bin/sh
#
# (C) Copyright NuoDB, Inc. 2019  All Rights Reserved

# Unfortunately, ksh93 defines builtin aliases even when run non-interactively.
unalias -a

die () { echo "$*"; exit 1; }

# Find the installation directory.
CMD=${0##*/}
DIR=`cd "${0%$CMD}." && pwd`

# Find the run-java-app script
_home="$NUOCLIENT_HOME"
[ -z "$_home" ] || [ -f "$NUOCLIENT_HOME"/etc/run-java-app.sh ] \
    || die "Cannot locate NuoDB client installation ($_home)"
[ -z "$_home" ] && [ -f "${DIR%/*}"/etc/run-java-app.sh ] \
    && _home="${DIR%/*}"
[ -n "$_home" ] || die "Cannot locate NuoDB client installation"

export NUODB_OPTSVAR=NUODB_MANAGER_JAVA_OPTS

# Force the configuration to be exported to the app
export NUODB_CFGDIR=

umask 0077

exec "$_home"/etc/run-java-app.sh jar/nuokeymanager.jar "NuoDB Key Manager" -- "$@"
